platform :ios, '17.0'

def privateSource(name, version)
  pod name, :git => 'https://github.com/TiagoLinharess/FinancialControl.git', :tag => version
end

target 'FinancialControlApp' do
  privateSource('Core', '0.1.0-core')
  privateSource('Provider', '0.1.4-provider')

  target 'FinancialControlAppTests' do
    inherit! :search_paths
  end

  target 'FinancialControlAppUITests' do
    # Pods for testing
  end

end
