platform :ios, '17.0'

target 'FinancialControlApp' do
  use_frameworks!
  
  pod 'Core', :git => 'https://github.com/TiagoLinharess/FinancialControl.git', :tag => '0.1.0-core'

  target 'FinancialControlAppTests' do
    inherit! :search_paths
  end

  target 'FinancialControlAppUITests' do
    # Pods for testing
  end

end

#def private_source(name, version)
#  return pod name, :git => 'https://github.com/TiagoLinharess/FinancialControl.git', :tag => version
#end
