# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Core' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Core

  target 'CoreTests' do
    # Pods for testing
  end

end

target 'CoreSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreSample

end
