# Uncomment the next line to define a global platform for your project
 platform :ios, '17.0'

def sharpnez_core_pod
  pod 'SharpnezCore', :git => 'https://github.com/TiagoLinharess/sdk-ios-sharpnez-core.git', :tag => '2.0.0'
end

target 'Provider' do
  sharpnez_core_pod
end

target 'ProviderSample' do
  sharpnez_core_pod
end
