# Uncomment the next line to define a global platform for your project
 platform :ios, '17.0'

def sharpnez_core_pod
  pod 'SharpnezCore', :git => 'https://github.com/TiagoLinharess/sdk-ios-sharpnez-core.git', :tag => '2.0.0'
end

target 'Provider' do
  # Comment the next line if you don't want to use dynamic frameworks
  sharpnez_core_pod

  target 'ProviderTests' do
    # Pods for testing
  end

end

target 'ProviderSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  sharpnez_core_pod

  # Pods for ProviderSample

end
